services:
  backend:
    build: ./backend
    image: tzuhan1007/ig-clone-backend:latest
    container_name: ig-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build: ./frontend
    image: tzuhan1007/ig-clone-frontend:latest
    container_name: ig-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped